global:
  container:
    requestsLimitsEnabled: true
  deploymentMode: development
  istio:
    sidecar:
      requestsLimitsEnabled: true
      resources:
        requests: {}
        limits: {}
  registry:
    ddmLanguageServer:
      container:
        envVars: {}
        resources:
          requests: {}
          limits: {}
      istio:
        sidecar:
          enabled: true
          resources:
            requests: {}
            limits: {}

name: ddm-language-server
replicaCount: 1

image:
  name: ddm-language-server
  version: latest

serviceAccount:
  create: true
  annotations: {}
  name: ddm-language-server

service:
  type: ClusterIP
  port: 8080

probes:
  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness

keycloak:
  realms:
    admin: admin
  certificatesEndpoint: /protocol/openid-connect/certs

appConfigMountPath: "/app/config"

############## EDP VARIABLES TEST VALUES ##############################
namespace: ns
cdPipelineName: pipe
cdPipelineStageName: dev
dnsWildcard: edp-epam.com

monitoring:
  namespace: openshift-monitoring
  prometheusScrapePath: /actuator/prometheus
  jobLabel: app
